name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Gportfolio/Gportfolio' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: yarn

      - name: Run eslint
        run: yarn lint

      - name: Run tests
        run: yarn test --coverage

      - name: Build project
        run: yarn build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
